# Add the CocoaPods source at the very top
# source 'https://github.com/CocoaPods/Specs.git'

# Resolve react_native_pods.rb with node
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Force static frameworks
use_frameworks! :linkage => :static

target 'snatchi' do
  config = use_native_modules!

  $RNFirebaseAsStaticFramework = true

  # Firebase (safe)
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  # RN Background Geolocation (installs TSBackgroundFetch internally)
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Fix arm64 simulators
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end