
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_KEY_FILEPATH"],
      duration: 1200,
      in_house: false
    )
    
    match(
      type: "appstore",
      api_key: api_key,
     git_url: "git@github.com:suftnetrepo/ios-certificates.git"

    )
    
    increment_build_number(xcodeproj: "snatchi.xcodeproj")
    
    build_app(
      scheme: "snatchi",
      workspace: "snatchi.xcworkspace",
      export_method: "app-store",
      clean: true
    )
    
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
